language: swift
osx_image: xcode11
install:
  - ./install_swiftlint.sh
before_install:
  - pod deintegrate
  - pod update
script:
  - swiftlint
  - xcodebuild -scheme HenriPotier -workspace HenriPotier.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.0' build test -quiet
after_success:
  - bash <(curl -s https://codecov.io/bash)